### ISSUE TITLE
Override assetic tags

### ISSUE THREAD

**Issue by Germanaz0** [hostnet/webpack-bundle#15]
For migration purposes it would be nice to override the assetic twig tags, in order to use webpack instead.

We also could log where it has been used to later migrate with the proper tags.

**Comment by haroldiedema** [comment]
Hi Germanaz0,

This was actually a consideration when building the bundle. However, since Symfony uses some of these tags internally - in its own bundles - this wasn't an option unfortunately.

**Comment by Germanaz0** [comment]
I'm pretty sure that this is gonna be fixed on SF3 when they remove Assetic as base component.

**Comment by iltar** [comment]
Even though for migration purposes it would be nice to override the tag, I think it would cause way too many issues to actually override it.
