### ISSUE TITLE
Untracked templates feature is missing?

### ISSUE THREAD

**Issue by iltar** [hostnet/webpack-bundle#23]
It's described to be shown in the profiler, but this private property is unused (only written to). Should this feature be removed or is it desired to be added in the future?

https://github.com/hostnet/webpack-bundle/blob/master/src/Component/Asset/Tracker.php#L69-L75

**Comment by haroldiedema** [comment]
Feel free to add. I didn't get around this yet.
While you're at it, could you also fill the 'Configuration' tab in the profiler?

It might be useful to see what is configured so you don't have to open the webpack configuration file (the one that is generated).

In the most simplest way, it's nothing more than a "file_get_contents" of the webpack.config.js file in the cache directory.

**Comment by iltar** [comment]
Sounds like a good idea, I found myself checking that file a couple of times. Maybe we can add a bit more debug information while at it.
