### ISSUE TITLE
Mistake in documentation : extract-text-webpack-plugin not webpack-extract-text-plugin

### ISSUE THREAD

**Issue by sebastienvermeille** [hostnet/webpack-bundle#48]
Hello first of all thank you for this bundle I am starting with SF3.* and I really appreciate this bundle concept.

I just figured out this small mistake on the documentation page :

You talk about installing webpack-extract-text-plugin and now it has an other name :
https://www.npmjs.com/package/extract-text-webpack-plugin

Just a little typo error

**Comment by hboomsma** [comment]
Fixed in #49
