### ISSUE TITLE
Webpack inline scripts brake on Windows/XAMPP

### ISSUE THREAD

**Issue by cgraefe** [hostnet/webpack-bundle#56]
I am currently using Windows and XAMPP for development. Webpack inline scripts do not work here, because file paths seem to be calculated inconsistently. The same template will be referred to in WebpackTockenParser as:

`D:\src\projectx\app\Resources\views\base.html.twig`

and in TwigParser as: 

`D:\src\projectx\app\Resources\views/base.html.twig`

This then results in different md5 checksums and WebpackTokenParser will return a WebpackInlineNode referencing a non-existing file.

**Comment by hboomsma** [comment]
@cgraefe Does this fix your problem?
I will create a new version by the end of the day (CEST)

**Comment by cgraefe** [comment]
@hboomsma Yes, the changes in pull request #57 did fix this problem for me. Thanks for merging!
