### ISSUE TITLE
Webpack 2 / 3 Support?

### ISSUE THREAD

**Issue by akester** [hostnet/webpack-bundle#76]
I have a use case from some additional plug-ins (SVG Sprites, image optimization, etc) but I guess I'd be a lot more comfortable building these for Webpack 2 or 3 vs Webpack 1.

Is updated Webpack support in the works?  I'd be happy to help contribute if help is needed.

**Comment by akester** [comment]
Secondary question, is this bundle still going to be supported with Symfony's new Encore system is released?

**Comment by yannickl88** [comment]
We have nothing in the works as of yet for updating webpack. You are welcome to send a PR however!

As to the second question. We are moving away from this bundle internally and might stop supporting this bundle in the future. With Symfony Encore and possible better solutions I'm not quite sure what this bundle add to value. Moreover, we have found that dynamically determining entry-points for webpack does not scale very well for large application.

That being said, for the time being we are still accepting any PR's to add or update functionally.
